### ISSUE TITLE
'Summon 〇〇' icon is missing

### ISSUE THREAD

**Issue by heipizhu4** [Sullien/The-Demon-World#11]
![image](https://user-images.githubusercontent.com/100454479/174467251-b1af09a7-f1c9-4e6e-809d-2b5cb64e524a.png)

**Comment by Sullien** [comment]
Update again. Should be fixed

**Comment by heipizhu4** [comment]
> Update again. Should be fixed

Did you update in the wrong place? I can't find it.

**Comment by heipizhu4** [comment]
Resolved by 92be1c6e89117534d2e492238397fb89a9368960. Thanks @Sullien
